<?php
// public_html/ops/install_user_model.php
// Bir kez çalıştır: ops/models/User.php dosyasını oluşturur. Sonra SİL!

ini_set('display_errors','1'); error_reporting(E_ALL);

$targetDir  = __DIR__ . '/models';
$targetFile = $targetDir . '/User.php';

if (!is_dir($targetDir)) { mkdir($targetDir, 0755, true); }

// User.php içeriği (base64 ile güvenli yazım)
$base64 = <<<'B64'
PD9waHAKLy8gcHVibGljX2h0bWwvb3BzL21vZGVscy9Vc2VyLnBocAovLyBOT1Q6IFBhcmVudCBN
b2RlbCB0aXAgYmlsZGlybWl5b3Ig4oCYYnUgYsSxbmZ0YSDDvGxmciBzbMSxbsSxZGEgZGEgcHTD
vHJ0eSB0eXBlIEtVTExBTk1JWVJPVVouCgpjbGFzcyBVc2VyIGV4dGVuZHMgTW9kZWwKewogICAg
cHJvdGVjdGVkICR0YWJsZSA9ICd1c2Vycyc7CiAgICBwcm90ZWN0ZWQgJHByaW1hcnlLZXkgPSAn
aWQnOwoKICAgIHByb3RlY3RlZCAkZmlsbGFibGUgPSBbCiAgICAgICAgJ3VzZXJuYW1lJywnZW1h
aWwnLCdwYXNzd29yZCcsJ2Z1bGxfbmFtZScsJ3JvbGUnLCdkZXBhcnRtZW50JywncG9zaXRpb24n
LAogICAgICAgICdwaG9uZScsJ2F2YXRhcicsJ2lzX2FjdGl2ZScsJ2xhc3RfbG9naW4nLCdsb2dp
bl9jb3VudCcsJ2ZhaWxlZF9hdHRlbXB0cycsCiAgICAgICAgJ2xvY2tlZF91bnRpbCcsJ3R3b19m
YWN0b3JfZW5hYmxlZCcsJ3R3b19mYWN0b3Jfc2VjcmV0JywnY3JlYXRlZF9hdCcsJ3VwZGF0ZWRf
YXQnCiAgICBdOwoKICAgIHByb3RlY3RlZCAkaGlkZGVuID0gWydwYXNzd29yZCcsJ3R3b19mYWN0
b3Jfc2VjcmV0J107CiAgICBwcm90ZWN0ZWQgJHRpbWVzdGFtcHMgPSB0cnVlOwoKICAgIHB1Ymxp
YyBmdW5jdGlvbiBmaW5kQnlFbWFpbChzdHJpbmcgJGVtYWlsKTogP2FycmF5CiAgICB7CiAgICAg
ICAgJHJvdyA9ICR0aGlzLT5maW5kQnkoJ2VtYWlsJywg bWJfc3RybG93ZXIodHJpbSgkZW1haWwp
KSk7CiAgICAgICAgcmV0dXJuICRyb3cgPyA6IG51bGw7CiAgICB9CgogICAgcHVibGljIGZ1bmN0
aW9uIHZlcmlmeVBhc3N3b3JkKGFycmF5ICR1c2VyLCBzdHJpbmcgJHBsYWluKTogYm9vbAogICAg
ewogICAgICAgIHJldHVybiBpc3NldCgkdXNlclsncGFzc3dvcmQnXSkmJiBwYXNzd29yZF92ZXJp
ZnkoJHBsYWluLCAoc3RyaW5nKSR1c2VyWydwYXNzd29yZCddKSk7CiAgICB9CgogICAgcHVibGlj
IGZ1bmN0aW9uIGNyZWF0ZVdpdGhQYXNzd29yZChhcnJheSAkZGF0YSk6IGludAogICAgewogICAg
ICAgIGlmIChlbXB0eSgkZGF0YVsncGFzc3dvcmQnXSkpIHsKICAgICAgICAgICAgdGhyb3cgbmV3
IEludmFsaWRBcmd1bWVudEV4Y2VwdGlvbignUGFyb2xhIGdlcmVrbGknKTsKICAgICAgICB9CiAg
ICAgICAgJGRhdGFbJ3Bhc3N3b3JkJ10gPSBwYXNzd29yZF9oYXNoKChzdHJpbmcpJGRhdGFbJ3Bh
c3N3b3JkJ10sIFBBU1NXT1JEX0RFRkFVTFQpOwogICAgICAgIGlmICghZW1wdHkoJGRhdGFbJ2Vt
YWlsJ10pKSB7CiAgICAgICAgICAgICRkYXRhWydlbWFpbCddID0gbWJfc3RybG93ZXIodHJpbSgo
c3RyaW5nKSAkZGF0YVsnZW1haWwnXSkpOwogICAgICAgIH0KICAgICAgICAkZGF0YSA9ICRkYXRh
ICsgWydpc19hY3RpdmUnPT4xLCdsb2dpbl9jb3VudCc9PjAsJ2ZhaWxlZF9hdHRlbXB0cyc9PjBd
OwogICAgICAgIHJldHVybiAkdGhpcy0+Y3JlYXRlKCRkYXRhKTsKICAgIH0KCiAgICBwdWJsaWMg
ZnVuY3Rpb24gaXNMb2NrZWQoYXJyYXkgJHVzZXIpOiBib29sCiAgICB7CiAgICAgICAgcmV0dXJu
ICFlbXB0eSgkdXNlclsnbG9ja2VkX3VudGlsJ10pICYmIHN0cnRvdGltZSgoc3RyaW5nKSR1c2Vy
Wydsb2NrZWRfdW50aWwnXSkgPiB0aW1lKCk7CiAgICB9CgogICAgcHVibGljIGZ1bmN0aW9uIHJl
Y29yZFN1Y2Nlc3NmdWxMb2dpbihpbnQgJHVzZXJJZCk6IGludAogICAgewogICAgICAgIHJldHVy
biAkdGhpcy0+dXBkYXRlQnlJZCgkdXNlcklkLCBbCiAgICAgICAgICAgICdsYXN0X2xvZ2luJz0+
ZGF0ZSgnWS1tLWQgSC1pLVMnKSwKICAgICAgICAgICAgJ2xvZ2luX2NvdW50Jz0+JHRoaXMtPnNh
ZmVJbmMoJHVzZXJJZCwnbG9naW5fY291bnQnKSwKICAgICAgICAgICAgJ2ZhaWxlZF9hdHRlbXB0
cyc9PjAsCiAgICAgICAgICAgICdsb2NrZWRfdW50aWwnPT5udWxsLAogICAgICAgIF0pOwogICAg
fQoKICAgIHB1YmxpYyBmdW5jdGlvbiByZWNvcmRGYWlsZWRMb2dpbihpbnQgJHVzZXJJZCwgaW50
ICRtYXhBdHRlbXB0cywgaW50ICRsb2Nrb3V0U2Vjb25kcyl6IGludAogICAgewogICAgICAgICRj
dXJyZW50ID0gJHRoaXMtPmZpbmQoJHVzZXJJZCk7CiAgICAgICAgJGZhaWxzID0gKGludCkoJGN1
cnJlbnRbJ2ZhaWxlZF9hdHRlbXB0cyddID8/IDApICsgMTsKICAgICAgICAkcGF5bG9hZCA9IFsn
ZmFpbGVkX2F0dGVtcHRzJz0+JGZhaWxzXTsKICAgICAgICBpZiAoJGZhaWxzID49ICRtYXhBdHRl
bXB0cykgewogICAgICAgICAgICAkcGF5bG9hZFsnbG9ja2VkX3VudGlsJ10gPSBkYXRlKCJZLW0t
ZCBILWk6UyIsIHRpbWUoKSArICRsb2Nrb3V0U2Vjb25kcyk7CiAgICAgICAgfQogICAgICAgIHJl
dHVybiAkdGhpcy0+dXBkYXRlQnlJZCgkdXNlcklkLCAkcGF5bG9hZCk7CiAgICB9CgogICAgcHJp
dmF0ZSBmdW5jdGlvbiBzYWZlSW5jKGludCAkdXNlcklkLCBzdHJpbmcgJGZpZWxkKTogaW50CiAg
ICB7CiAgICAgICAgJHJvdyA9ICR0aGlzLT5maW5kKCR1c2VySWQpOwogICAgICAgICR2YWwgPSAo
aW50KSkoJHJvd1skZmllbGRdID8/IDApICsgMTsKICAgICAgICByZXR1cm4gJHRoaXMtPnVwZGF0
ZUJ5SWQoJHVzZXJJZCwgWyRmaWVsZCA9PiR2YWxdKTsKICAgIH0KfQo=
B64;

$content = base64_decode($base64);

if (file_put_contents($targetFile, $content) === false) {
    echo 'ERROR: could not write file.';
    exit;
}
@chmod($targetFile, 0644);

echo 'OK: wrote ' . $targetFile . PHP_EOL;
clearstatcache(true, $targetFile);
echo 'EXISTS: ' . (is_file($targetFile) ? 'YES' : 'NO') . ' | SIZE: ' . filesize($targetFile) . PHP_EOL;
echo 'Done. Delete install_user_model.php after this.';